routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
Route::get('install', function() {

    Artisan::call('migrate:refresh',['--force'=>true,'--seed'=>true]);

});
*/





Route::get('/', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/ver-producto/{id?}', 'ProductController@viewId')->name('product.view');
Route::get('/comprar-producto/{id?}', 'ProductController@buy')->name('product.buy');
Route::get('/checkout-producto/{id?}', 'ProductController@checkout')->name('product.checkout');

Route::get('/get-order/{id?}', 'PaymentController@GenerateSingleBuy')->name('product.get.order');

//partials date
Route::get('/guardar-orden/{id?}', 'PurchaseOrderController@purchase')->name('purchase.order.single');

//mp
Route::get('/compra-exitosa', 'PaymentController@success')->name('collections.success');
Route::get('/compra-fallida', 'PaymentController@fail')->name('collections.fails');
Route::get('/compra-cancelar', 'PaymentController@pending')->name('collections.pending');

//fin mp

Route::namespace('admin')->prefix('/admin')->name('admin.')->group(function(){
    Route::get('/admin', 'ProductsController@index')->name('product.index');

    Route::get('/nuevo-producto', 'ProductsController@create')->name('product.create');
    Route::post('/actualizar-producto', 'ProductsController@update')->name('product.update');
    Route::post('/guardar-producto', 'ProductsController@save')->name('product.save');
    Route::post('/buscar-producto', 'ProductsController@search')->name('product.search');
    Route::post('/eliminar-producto', 'ProductsController@delete')->name('product.delete');

    /**Usuarios */
        Route::get('/usuarios','UsersController@index')->name('users');
        Route::get('/mi-usuario/{id?}','UsersController@edit')->name('edit.user');
        Route::post('/guardar-usuario-/{id?}','UsersController@store')->name('store.user');
        Route::get('/eliminar-usuario/{id?}','UsersController@delete')->name('delete.user');
        Route::get('/servicio-usuario','UsersController@search')->name('search.user');
        Route::get('/home', 'HomeController@index')->name('home');
    
        /**Ventas */
        Route::get('/ventas','BuysController@index')->name('buys');
        Route::get('/mi-venta/{id?}','BuysController@edit')->name('edit.buy');
        Route::post('/guardar-venta-/{id?}','BuysController@store')->name('store.buy');
        Route::get('/eliminar-venta/{id?}','BuysController@delete')->name('delete.buy');
        Route::post('/buscar-venta', 'BuysController@search')->name('search.buy');

});





Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{    use HasRoles;

    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','provider','photo','username','lastname','is_active','cellphone',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function user()
    {
        return $this->hasMany('App\User');
    }
    public function delivery()
    {
        return $this->belongsTo('App\sending');
    }
    public function scopeCustomer($query,$customer_id)
    {
        return $query->where('customer_id',$customer_id);
    }
    public function scopeName($query,$param)
    {
        if ($param != null) {
            return $query->where('name','LIKE','%'.$param.'%');
        }
    }
    public function scopeUserName($query,$param)
    {
        if ($param != null) {
            return $query->where('username','LIKE','%'.$param.'%');
        }
    }

}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    //
}

app/Http/Controllers/admin/UsersController.php
<?php


namespace App\Http\Controllers\admin;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;
use Spatie\Permission\Models\Role;

class UsersController extends Controller
{
  public function __construct()
  {
      $this->middleware('auth');
  }

    public function index()
    {
       $users=User::all();
       return view('admin.users.index',compact('users'));
    }
    public function edit($user_id=0)
    {
    
        if ($user_id==0) {
        return view('admin.users.edit');  
          
        }else{

        $users=User::with('roles')->where('id','=',$user_id)->get();
      return view('admin.users.edit')
      ->with('users',$users);
        }
      
     }
     public function search(Request $request)
     {
         $datas=$request->except('_token');
         $users= User::Name($datas['name'])
         ->UserName($datas['username'])
         ->orderBy('id','DESC')->get();
       return view('admin.users.index',compact('users'));
     
    }
    public function searchuser($id,Request $request)
    {
      $users=User::join('users','users.users_id','users.id')
      ->where('publications_id','=',$id)
      ->where($request->input('filter'),'LIKE','%'.$request->input('search')."%")->orderBy('users.id','DESC')
      ->with('users')->with('publications')
      ->get();
      return view('admin.users.index')
      ->with('users',$users)
      ->with('publications_id',$id);
    }
    public function update(Request $request)
    {
      $data= $request->except('_token','photo','role','password_confirmation','password');

      if ($request->input('password')=="") {
        $validatedData = $request->validate([
          'name' => ['required', 'string', 'max:255'],
          'email' => ['required',Rule::unique('users')->ignore($request->input('id'))],
          'role' => ['required','min:3'],
  
        ]);

      }else{
 
        $validatedData = $request->validate([
          'name' => ['required', 'string', 'max:255'],
          'email' => ['required',Rule::unique('users')->ignore($request->input('id'))],
          'password' => ['required', 'string', 'min:8', 'confirmed'],
          'role' => ['required','min:3'],
  
        ]);
        $data['password']=Hash::make($request->input('password'));
      }

        
          $user=User::where('id','=',$request->input('id'))->update($data);
          return response()->json(['result'=>$request->input('id')]);

    }
 
    public function store(Request $request)
    {

      if($request->has('id')){
        $data= $request->except('_token','photo','password_confirmation','password','role');

        if ($request->has('password') && $request->input('password') == '') {
          $validatedData = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required',Rule::unique('users')->ignore($request->input('id'))],
          ],
          [
            'email.unique' => "El email de acceso ya está en uso,por favor introduzca uno nuevo",
          ]
        );

 

      }else{
        
          $validatedData = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required',Rule::unique('users')->ignore($request->input('id'))],
            'password' => ['required', 'string', 'confirmed'],
          ],
          [
            'email.unique' => "El email de acceso ya está en uso,por favor introduzca uno nuevo",
          ]
        );
        $data['password']=Hash::make($request->input('password'));  

        }
        if ($request->has('is_active')) {
          $data['is_active']=1;
        }else{
          $data['is_active']=0;
        }

          $user=User::where('id','=',$request->input('id'))->update($data);
          $user=User::find($request->input('id'));
          if (in_array($request->input('role'),Role::all()->pluck('name')->toArray())) {
            $user->syncRoles($request->input('role'));
          }
          return response()->json(['result'=>$request->input('id')]);

   
      }else{
        $validatedData = $request->validate([
          'name' => ['required', 'string', 'max:255'],
          'email' => ['required','unique:users'],
          'password' => ['required', 'string', 'confirmed'],
        ],
        [
          'email.unique' => "El email de acceso ya está en uso,por favor introduzca uno nuevo",
          ]
      );
        $data= $request->except('_token','photo','role');
        $data['password']=Hash::make($request->input('password'));
      //  $data['customer_id']=Auth::user()->customer_id;

        if ($request->has('is_active')) {
          $data['is_active']=1;
        }else{
          $data['is_active']=0;
        }
        $user=User::create($data);

        if (in_array($request->input('role'),Role::all()->pluck('name')->toArray())) {
            $user->assignRole($request->input('role'));    
          }

      }


      if ($request->hasFile('photo')) {
        $file = $request->file('photo');
        $allowedfileExtension=['jpg','png','jpeg'];
         $extension = $file->getClientOriginalExtension();
         $check=in_array($extension,$allowedfileExtension);
          if($check){
              $user->photo="foto"."-".$user->id.'.'.$extension;
              $user->save();
              $path = $file->storeAs('users/'.$user->id,$user->photo);
            }
        
       }

      return response()->json(['result'=>$user->id]);

    }
    public function delete($id){
      if ($id != 'id') {
        $user= User::find($id);
        $user->delete();
        return response()->json(['result'=>1]);
      }else{
        return response()->json(['result'=>-1]);

      }
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')
@section('content')
  <div class="col-lg-12 col-md-12 col-12 col-sm-12">

        <div class="card">
            <div class="card-header" data-background-color="blue">
                @isset($users)
                <h4 class="title">Editar Usuario</h4>
                @else
                <h4 class="title">Nuevo Usuario</h4>

                @endisset
            </div>
            <div class="card-content table-responsive">
                <form class="form-horizontal" method="post" onsubmit="save(event)"  id="form_user" action="{{route('admin.store.user')}}"
                    role="form">
                    @csrf
                    @isset($users)
                    @foreach ($users as $user)
            <input type="hidden" name="id" value="{{$user->id}}">
                    @include("admin.partials.form-user")
    
                    @endforeach
                    @else
                 @include("admin.partials.form-user")

                @endisset
                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-10">
                         
                        @isset($users)
                        <button type="submit" class="btn btn-primary">Actualizar Usuario</button>
                        @else
                        <button type="submit" class="btn btn-primary">Guardar Usuario</button>
                    
                        @endisset
                        </div>
                      </div>
                </form>
            </div>
        </div>
    </div>

@endsection
@section('scripts')
<script src="{{asset('js/sweetalert.min.js')}}" type="text/javascript"></script>

<script>

    function save(e) {
        e.preventDefault();
        var formdata = new FormData($("#form_user")[0]);
            $.ajax({
                url         : "{{route('admin.store.user')}}",
                data        : formdata,
                cache       : false,
                contentType : false,
                processData : false,
                type        : 'POST',
                dataType:"JSON",
                beforeSend:function() {
                  swal("Por favor espera,tu petición se está procesando!", {
                    buttons: false,
                    
                  });
                },
                success: function(data, textStatus, jqXHR){
                    if (data.result != null) {
                      swal({
                        tittle:"Excelente!",
                        text:"Cambios guardados con éxito,será redirigido a continuación",
                        icon :"success",
                      }).then((value) => {
                        //let url="{{route('admin.edit.user',['id'=>0])}}"
                        //url=url.replace('0',data.result);
                        location.href='{!! url()->previous()!!}';//url;
                      });
                    }else{
                      swal("Ups!",data.message,"error");   
                    }

                  },
                  error:function(data,message,res){
                    let lista= "<ul>";
                for(var k in data.responseJSON.errors) {
                lista += "<li>"+ data.responseJSON.errors[k][0] +"</li>";              
                }
                
              lista+="</ul>";
              let au='<div class="alert alert-danger msj" role="alert">'+lista+'</div>';

                      swal({
                      title: 'Ups!',
                      text: 'Hubo un error',
                      html: lista,
                      type: 'error',
                    });

                   // swal("ups!","Hubo un error al procesar tu petición,vuelve a intentar por favor","error");
                  },
                  statusCode:{
                    422:function(data) {

                      console.log(data.responseJSON.errors);
                      let lista= "";
                for(var k in data.responseJSON.errors) {
                lista += ""+ data.responseJSON.errors[k][0] +"";              
                }
                
              lista+="";
              let au='<div class="alert alert-danger msj" role="alert">'+lista+'</div>';

                      swal({
                      title: 'Ups!',
                      text: 'Hubo un error: '+lista,
                      icon: 'error',
                    });                    }
                  }
            });
    }
</script>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin')
@section('content')
<div class=" col-lg-12 col-md-12 col-12 col-sm-12">
  <div class="btn-group pull-right">

</div>
<div class="card">
  <div class="card-header" id="top">
      <h4 class="title" id="encabezados">Usuarios</h4>
  </div>
  <div class="card-content table-responsive">
	
	<form method="get" action="{{route('admin.search.user')}}" role="form"  class="form-horizontal">
    @csrf
    <input type="hidden" name="view" value="users">
	<div class="row">
			<div class="col-lg-3 col-4 col-sm-4">
				<input type="tel" name="name" placeholder="Nombre..." class="form-control">
			</div>
			<div class="col-lg-3 col-4 col-sm-4">
				<input type="text" name="username" placeholder="Nombre usuario..." class="form-control">           				
			</div>
			<div class="col-lg-3 col-4 col-sm-4">
        <button class="btn btn-secondary" >Buscar</button>

      </div>
    </div>
    <br>
    <div class="row mt-4">

			<div class="col-lg-12 col-12 col-sm-12 text-center">
            <a href="{{route('admin.edit.user')}}" class="btn btn-primary"><i class='fa fa-male'></i> Nuevo Usuario</a>
			</div>
			
		</div>
  </div>
	</form>
			<div class="table-responsive mt-3">
			<table class="table table-bordered table-hover">
			<thead>
			<th>Nombre completo</th>
			<th>Usuario de acceso</th>
			<th>Fecha de alta</th>
			<th></th>
            </thead>
            @if (count($users)>0)
                
			@foreach($users as $user)
				
				<tr>
                <td>{{$user->name}}</td>
                <td>{{$user->email}}</td>
                <td>{{$user->created_at}}</td>
				<td style="width:280px;">
                <!--<a href="" class="btn btn-default btn-xs">Historial</a>-->
                <a href="{{route('admin.edit.user',$user->id)}}" class="btn btn-warning btn-xs">Editar</a>
				<a href="javascript:;" data-id_user={{$user->id}} onclick="eliminar(this);" class="btn btn-danger btn-xs">Eliminar</a>
				</td>
				</tr>
            @endforeach
            @else
            <p class='alert alert-danger'>No hay registros</p>
            @endif

      </table>
    </div>
			</div>
			</div>

@endsection


@section('scripts')
<script src="{{asset('js/sweetalert.min.js')}}" type="text/javascript"></script>

<script>

function eliminar(a) {
          swal({
            icon: "warning",
              text: '¿Seguro que deseas eliminar este Usuario?,se borrarán todos los datos relacionados con él,esto no se  puede revertir!".',
              buttons: {
                  cancel: "No,cancelar!",
                  catch: {
                    text: "Sí,eliminar",
                    value: "catch",
                  },
                },
              })
              .then((value) => {
                switch (value) {
                  case "catch":
               let id_user=$(a).data("id_user");
               let url="{{route('admin.delete.user','id')}}"
               url=url.replace("id",id_user);
                $.ajax({
                url         : url,
                cache       : false,
                contentType : false,
                processData : false,
                type        : 'get',
                dataType:"JSON",
                success     : function(data, textStatus, jqXHR){
                    if (data.result != -1) {
                      swal({
                        tittle:"Excelente!",
                        text:"Usuario eliminado con éxito",
                        icon :"success",
                      }).then((value) => {
                        location.href='{{route("admin.users")}}';


                      });

                    }else{

                    }
               
                  },
				  error:function(data,message,res){
                    let lista= "<ul>";
                for(var k in data.responseJSON.errors) {
                lista += "<li>"+ data.responseJSON.errors[k][0] +"</li>";              
                }
                
              lista+="</ul>";
              let au='<div class="alert alert-danger msj" role="alert">'+lista+'</div>';

                      swal({
                      title: 'Ups!',
                      text: 'Hubo un error',
                      html: lista,
                      type: 'error',
                    });

                   // swal("ups!","Hubo un error al procesar tu petición,vuelve a intentar por favor","error");
                  }
            });
                    break;
                  default:
                  
                }
              });
        

      }   

</script>
@endsection