routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
Route::get('install', function() {

    Artisan::call('migrate:refresh',['--force'=>true,'--seed'=>true]);

});
*/





Route::get('/', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/ver-producto/{id?}', 'ProductController@viewId')->name('product.view');
Route::get('/comprar-producto/{id?}', 'ProductController@buy')->name('product.buy');
Route::get('/checkout-producto/{id?}', 'ProductController@checkout')->name('product.checkout');

Route::get('/get-order/{id?}', 'PaymentController@GenerateSingleBuy')->name('product.get.order');

//partials date
Route::get('/guardar-orden/{id?}', 'PurchaseOrderController@purchase')->name('purchase.order.single');

//mp
Route::get('/compra-exitosa', 'PaymentController@success')->name('collections.success');
Route::get('/compra-fallida', 'PaymentController@fail')->name('collections.fails');
Route::get('/compra-cancelar', 'PaymentController@pending')->name('collections.pending');

//fin mp

Route::namespace('admin')->prefix('/admin')->name('admin.')->group(function(){
    Route::get('/admin', 'ProductsController@index')->name('product.index');

    Route::get('/nuevo-producto', 'ProductsController@create')->name('product.create');
    Route::post('/actualizar-producto', 'ProductsController@update')->name('product.update');
    Route::post('/guardar-producto', 'ProductsController@save')->name('product.save');
    Route::post('/buscar-producto', 'ProductsController@search')->name('product.search');
    Route::post('/eliminar-producto', 'ProductsController@delete')->name('product.delete');

    /**Usuarios */
        Route::get('/usuarios','UsersController@index')->name('users');
        Route::get('/mi-usuario/{id?}','UsersController@edit')->name('edit.user');
        Route::post('/guardar-usuario-/{id?}','UsersController@store')->name('store.user');
        Route::get('/eliminar-usuario/{id?}','UsersController@delete')->name('delete.user');
        Route::get('/servicio-usuario','UsersController@search')->name('search.user');
        Route::get('/home', 'HomeController@index')->name('home');
    
        /**Ventas */
        Route::get('/ventas','BuysController@index')->name('buys');
        Route::get('/mi-venta/{id?}','BuysController@edit')->name('edit.buy');
        Route::post('/guardar-venta-/{id?}','BuysController@store')->name('store.buy');
        Route::get('/eliminar-venta/{id?}','BuysController@delete')->name('delete.buy');
        Route::post('/buscar-venta', 'BuysController@search')->name('search.buy');

});





Auth::routes();

app/Http/Controllers/BuysController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BuysController extends Controller
{
    //
}

app/Http/Controllers/admin/BuysController.php
<?php

namespace App\Http\Controllers\admin;
use App\Http\Controllers\Controller;
use App\invoice;
use App\invoice_detail;
use App\Products;
use App\sending;
use App\status;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BuysController extends Controller
{
  public function __construct()
  {
      $this->middleware('auth');
  }

    public function index()
    {
     if(Auth::user()->hasRole('admin')){
      $buys=invoice::with('user')->with('sending.delivery')->join('statuses','statuses.id','invoices.status')->select('invoices.*','statuses.name as status')->orderBy('created_at','desc')->get();
      return view('admin.buys.index')->with('buys',$buys);
     }
     if(Auth::user()->hasRole('delivery')){
      $buys=sending::where('delivery_id',Auth::user()->id)->with('invoice.detail')->orderBy('created_at','desc')->get();

   //   $buys=invoice::with('user')->with('sending.delivery')->join('statuses','statuses.id','invoices.status')->select('invoices.*','statuses.name as status')->orderBy('created_at','desc')->get();
      return view('admin.buys.delivery')->with('buys',$buys);
     }
    }

    public function edit($id=0)
    {
     if($id==0){
         $customers= User::orderBy('lastname','desc')->get();
         $products=Products::orderBy('name','desc')->get();
         $employees= User::role('delivery')->get();
         
         return view('admin.buys.edit',compact('employees','customers','products'));   
       }else{
        $customers= User::orderBy('lastname','desc')->get();
        $products=Products::orderBy('name','desc')->get();
        $employees= User::role('delivery')->get();
        $buy=invoice::with('user')->with('detail')->with('sending.delivery')->join('statuses','statuses.id','invoices.status')->select('invoices.*','statuses.name as status')->where('invoices.id',$id)->first();
        return view('admin.buys.edit',compact('buy','employees','customers','products'));   
       }
    }
    public function search(Request $request)
    {
        $datas=$request->except('_token');
        $users= User::Name($datas['name'])
        ->UserName($datas['username'])
        ->orderBy('id','DESC')->get();
      return view('admin.users.index',compact('users'));
    
   }
   public function searchuser($id,Request $request)
   {
     $users=User::join('users','users.users_id','users.id')
     ->where('publications_id','=',$id)
     ->where($request->input('filter'),'LIKE','%'.$request->input('search')."%")->orderBy('users.id','DESC')
     ->with('users')->with('publications')
     ->get();
     return view('admin.users.index')
     ->with('users',$users)
     ->with('publications_id',$id);
   }
   public function update(Request $request)
   {
     $data= $request->except('_token','photo','role','password_confirmation','password');

     if ($request->input('password')=="") {
       $validatedData = $request->validate([
         'name' => ['required', 'string', 'max:255'],
         'email' => ['required',Rule::unique('users')->ignore($request->input('id'))],
         'role' => ['required','min:3'],
 
       ]);

     }else{

       $validatedData = $request->validate([
         'name' => ['required', 'string', 'max:255'],
         'email' => ['required',Rule::unique('users')->ignore($request->input('id'))],
         'password' => ['required', 'string', 'min:8', 'confirmed'],
         'role' => ['required','min:3'],
 
       ]);
       $data['password']=Hash::make($request->input('password'));
     }

       
         $user=User::where('id','=',$request->input('id'))->update($data);
         return response()->json(['result'=>$request->input('id')]);

   }

   public function store(Request $request)
   {
         $validatedData = $request->validate([
           'total' => ['required','integer','min:1'],
           'place_buy' => ['required', 'string'],
         ],
         [
           'total.integer' => "El total no puede ser 0",
         ]
       );
      
       if (!is_numeric($request->customer_id)) {
        $customer= User::create([
          'name'=>$request->customer_id,
          'cellphone'=>$request->cellphone
        ]);
        $customer->assignRole('user');
        $request->customer_id=$customer->id;
      }else{
        $customer=User::find($request->customer_id);
      }
            
      if (!is_numeric($request->product_id)) {
        $product= Products::create([
          'name'=>$request->input('product_id','No definido'),
          'offer_price'=>$request->total,
          'active'=>'no',

        ]);
        $request->product_id=$product->id;
      }else{
        $product=Products::find($request->product_id);
        $request->product_id=$product->id;
      }

      
       if($request->place_buy=='delivery' && $request->delivery_id != ''){
        $invoice=invoice::create([
          'name'=>$customer->name,
          'total'=>$request->total,
          'cellphone'=>$request->cellphone,
          'pay'=>$request->pay,
          'total_delivery'=>$request->total_delivery,
          'status'=> 1,
          'customer_id'=>$customer->id,
          'modified_id'=>Auth::user()->id,
          'creatur_id'=>Auth::user()->id,
                  ]);
          $sending= sending::create([
            'delivery_id'=>$request->delivery_id,
            'invoice_id'=>$invoice->id,
            'time_at'=>$request->time_at,
            'date'=>date('Y-m-d'),
            'status'=>1,
            'latitude'=>$request->lat,
            'longitude'=>$request->long,
          
          ]);
        

       }else{
        $invoice=invoice::create([
          'name'=>$customer->name,
          'total'=>$request->total,
          'cellphone'=>$request->cellphone,
          'pay'=>$request->pay,
          'total_delivery'=>0,
          'status'=> 2,
          'creatur_id'=>Auth::user()->id,
          'modified_id'=>Auth::user()->id,
          'customer_id'=>$customer->id,


        ]);
       }

       invoice_detail::create([
         'name'=>$product->name,
         'product_id'=>$product->id,
         'quantity'=>1,
         'price'=>$product->offer_price,
         'discount'=>0,
         'invoice_id'=>$invoice->id
       ]);
     
      


     return response()->json(['result'=>$invoice->id]);

   }
   public function delete($id){
     if ($id != 'id') {
       $user= invoice::find($id);
       $user->delete();
       return response()->json(['result'=>1]);
     }else{
       return response()->json(['result'=>-1]);

     }
   }
}

resources/views/admin/buys/delivery.blade.php
@extends('layouts.admin')
@section('content')
	<div class=" col-lg-12 col-md-12 col-12 col-sm-12">
<div class="card">
  <div class="card-header" id="top">
      <h4 class="title" id="encabezados">Ventas</h4>
  </div>
  <div class="card-body ">
 
  <form class="form-horizontal" method="get" action="{{route('admin.search.buy')}}" role="form">
    @csrf

  <div class="form-group">
    <div class="col-lg-2">
      <label for="inputEmail1" class="col-lg-2 control-label">-</label>
    </div>
    <div class="col-lg-6">
      <select id="service_id" name="service_id" class="form-control" >
    </div>
  </div>
  <div class="form-group">
  <div class="col-lg-4">
		<div class="input-group">
		  <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
		  <input type="date" name="date_at" value="" class="form-control" placeholder="Palabra clave">
		</div>
    </div>
    <div class="col-lg-2">
    	<button class="btn  btn-secondary" style="margin: 0px 0px 20px 0px">Buscar</button>
    </div>
  </div>
</form>
       
<div class="form-group text-center">
    <a href="{{route('admin.edit.buy')}}" class="btn btn-primary text-center m-4">+ Nueva Venta</a>

</div>
<div class="table-responsive">

            @if (count($buys)>0)
			<table class="table table-bordered table-hover">
			<thead>
      <th>Fecha/Hora</th>
      <th>Cliente</th>
			<th>Total</th>
      <th>Cobro</th>

      <th></th>

			</thead>
            @foreach($buys as $buy)
            <tr>
            <td>{{$buy->created_at}}</td>
            <td>{{$buy->invoice->name}}</td>
            <td>${{$buy->invoice->total}}</td>
            <td>{{$buy->invoice->pay}}</td>

            <td style="width:280px;">
            <!--<a href="" class="btn btn-default btn-xs">Historial</a>-->
           {{--<a href="{{route('admin.edit.buy',$buy->id)}}" class="btn btn-warning btn-xs">Editar</a> --}}
           <a href="{{route('admin.view.request',$buy->id)}}" data-id_buy={{$buy->id}} class="btn btn-primary btn-xs">Ir al pedido</a>
            </td>
            </tr>
            @endforeach
            @else
            <p class='alert alert-danger'>No hay Ventas</p>
            @endif
            </table>
        </div>

			</div>
			</div>

	</div>
@endsection
@section('scripts')
<script src="{{asset('js/sweetalert.min.js')}}" type="text/javascript"></script>

<script>
    function eliminar(a) {
          swal({
            icon: "warning",
              text: '¿Seguro que deseas eliminar esto?,se borrarán todos los datos relacionados con él,esto no se  puede revertir!".',
              buttons: {
                  cancel: "No,cancelar!",
                  catch: {
                    text: "Sí,eliminar",
                    value: "catch",
                  },
                },
              })
              .then((value) => {
                switch (value) {
                  case "catch":
               let id_buy=$(a).data("id_buy");
               let url="{{route('admin.delete.buy','id')}}"
               url=url.replace("id",id_buy);
                $.ajax({
                url         : url,
                cache       : false,
                contentType : false,
                processData : false,
                type        : 'get',
                dataType:"JSON",
                success     : function(data, textStatus, jqXHR){
                    if (data.result != -1) {
                      swal({
                        tittle:"Excelente!",
                        text:"registro eliminado con éxito",
                        icon :"success",
                      }).then((value) => {
                        location.href='{{route("admin.buys")}}';


                      });

                    }else{

                    }
               
                  }
            });
                    break;
                  default:
                  
                }
              });
        

      }   

    </script>    
@endsection

resources/views/admin/buys/edit.blade.php
@extends('layouts.admin')
@section('css')
<link href="{{asset('css/select2.min.css')}}" rel="stylesheet"/>
   <style>
        /* Set the size of the div element that contains the map */
        #map {
        height: 400px;  /* The height is 400 pixels */
        width: 100%;  /* The width is the width of the web page */
       }

   </style>
@endsection
@section('content')
    <div class="col-md-12">

        <div class="card">
            <div class="card-header" data-background-color="blue">
                @isset($users)
                <h4 class="title">Editar Venta</h4>
                @else
                <h4 class="title">Nueva Venta</h4>

                @endisset
            </div>
            <div class="card-content table-responsive">
                <form class="form-horizontal" method="post" onsubmit="save(event)"  id="form_buy" "
                    role="form">
                    @csrf
                    @isset($users)
                    @foreach ($users as $user)
            <input type="hidden" name="id" value="{{$user->id}}">
                    @include("admin.partials.form-user")
    
                    @endforeach
                    @else
                 @include("admin.partials.form-buy")

                @endisset
                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-10">
                         
                        @isset($users)
                        <button type="submit" class="btn btn-primary">Actualizar Venta</button>
                        @else
                        <button type="submit" class="btn btn-primary">Guardar Venta</button>
                    
                        @endisset
                        </div>
                      </div>

                </form>
            </div>
        </div>
    </div>

@endsection
@section('scripts')
<script src="{{asset('js/select2.min.js')}}" type="text/javascript"></script>
<script src="{{asset('js/es.js')}}" type="text/javascript"></script>
<script src="{{asset('js/sweetalert.min.js')}}" type="text/javascript"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
<script
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDmTjC5yZKTVWz9w2YR88A1wNRAIy2iFIM&callback=initMap&libraries=&v=weekly"
  defer
></script>

<script>
   var lat='';
   var lng='';
   var marker='';
$(function(){
  @isset($buy->sending[0]->latitude)
  var coord={
    lat: {{$buy->sending[0]->latitude}},
    lng: {{$buy->sending[0]->longitude}}
  }
  @else
  var coord={
    
    lat: -29.423385,
    lng: -66.866722
  }
  @endisset
  var map = new google.maps.Map(document.getElementById('map'), {
    center: coord,
    zoom:15
  });
   marker = new google.maps.Marker({
    position:coord, 
    map: map,
    draggable: true
  });

  var searchBox = new google.maps.places.SearchBox(document.getElementById('searchmap'));
  google.maps.event.addListener(searchBox,'places_changed',function(){
    var places = searchBox.getPlaces();
    var bounds = new google.maps.LatLngBounds();
    var i,place;
    for(i=0; place=places[i]; i++){
      bounds.extend(place.geometry.location);
      marker.setPosition(place.geometry.location);
    }
    map.fitBounds(bounds);
    map.setZoom(15);
  });

  google.maps.event.addListener(marker,'position_changed',function(){
   lat = marker.getPosition().lat();
     lng = marker.getPosition().lng();
    $('#lat').val(lat);
    $('#long').val(lng);
    alert(lng)
    
  });
});

$("#place_buy").change(function() {
  if(this.value=='local'){
    $("#div_with_delivery").hide();

  }else{
    $("#div_with_delivery").show();
  }
});

    </script>

<script>
    $('.select2').select2({
  language: "es",
  tags: true,
  theme: "classic"
});

    function save(e) {
      e.preventDefault();

      lat = marker.getPosition().lat();
     lng = marker.getPosition().lng();
        $('#lat').val(lat);
    $('#long').val(lng);
        var formdata = new FormData($("#form_buy")[0]);
            $.ajax({
                url         : "{{route('admin.store.buy')}}",
                data        : formdata,
                cache       : false,
                contentType : false,
                processData : false,
                type        : 'POST',
                dataType:"JSON",
                beforeSend:function() {
                  swal("Por favor espera,tu petición se está procesando!", {
                    buttons: false,
                    
                  });
                },
                success: function(data, textStatus, jqXHR){
                    if (data.result != null) {
                      swal({
                        tittle:"Excelente!",
                        text:"Cambios guardados con éxito,será redirigido a continuación",
                        icon :"success",
                      }).then((value) => {
                        //let url="{{route('admin.edit.user',['id'=>0])}}"
                        //url=url.replace('0',data.result);
                        location.href='{!! url()->previous()!!}';//url;
                      });
                    }else{
                      swal("Ups!",data.message,"error");   
                    }

                  },
                  error:function(data,message,res){
                    let lista= "<ul>";
                for(var k in data.responseJSON.errors) {
                lista += "<li>"+ data.responseJSON.errors[k][0] +"</li>";              
                }
                
              lista+="</ul>";
              let au='<div class="alert alert-danger msj" role="alert">'+lista+'</div>';

                      swal({
                      title: 'Ups!',
                      text: 'Hubo un error',
                      html: lista,
                      type: 'error',
                    });

                   // swal("ups!","Hubo un error al procesar tu petición,vuelve a intentar por favor","error");
                  },
                  statusCode:{
                    422:function(data) {

                      console.log(data.responseJSON.errors);
                      let lista= "";
                for(var k in data.responseJSON.errors) {
                lista += ""+ data.responseJSON.errors[k][0] +"";              
                }
                
              lista+="";
              let au='<div class="alert alert-danger msj" role="alert">'+lista+'</div>';

                      swal({
                      title: 'Ups!',
                      text: 'Hubo un error: '+lista,
                      icon: 'error',
                    });                    }
                  }
            });
    }
</script>
@endsection

resources/views/admin/buys/index.blade.php
@extends('layouts.admin')
@section('content')
	<div class=" col-lg-12 col-md-12 col-12 col-sm-12">
<div class="card">
  <div class="card-header" id="top">
      <h4 class="title" id="encabezados">Ventas</h4>
  </div>
  <div class="card-body ">
 
  <form class="form-horizontal" method="get" action="{{route('admin.search.buy')}}" role="form">
    @csrf

  <div class="form-group">
    <div class="col-lg-2">
      <label for="inputEmail1" class="col-lg-2 control-label">-</label>
    </div>
    <div class="col-lg-6">
      <select id="service_id" name="service_id" class="form-control" >
    </div>
  </div>
  <div class="form-group">
  <div class="col-lg-4">
		<div class="input-group">
		  <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
		  <input type="date" name="date_at" value="" class="form-control" placeholder="Palabra clave">
		</div>
    </div>
    <div class="col-lg-2">
    	<button class="btn  btn-secondary" style="margin: 0px 0px 20px 0px">Buscar</button>
    </div>
  </div>
</form>
       
<div class="form-group text-center">
    <a href="{{route('admin.edit.buy')}}" class="btn btn-primary text-center m-4">+ Nueva Venta</a>

</div>
<div class="table-responsive">

            @if (count($buys)>0)
			<table class="table table-bordered table-hover">
			<thead>
        <th>Fecha</th>
            <th>Cliente</th>
			<th>Total</th>
      <th>Cobro</th>
      <th>Delivery</th>

      <th>Estado</th>

      <th>Creador</th>

      <th></th>

			</thead>
            @foreach($buys as $buy)
            <tr>
            <td>{{$buy->created_at}}</td>
            <td>{{$buy->name}}</td>
            <td>${{$buy->total}}</td>
            <td>{{$buy->pay}}</td>
            <td>@if ($buy->total_delivery ==0)
                NO
                @else
                {{$buy->sending[0]->delivery->name}}
            @endif</td>
            <td>{{$buy->status}}</td>
            <td>{{$buy->user->name}}</td>

            <td style="width:280px;">
            <!--<a href="" class="btn btn-default btn-xs">Historial</a>-->
           {{--<a href="{{route('admin.edit.buy',$buy->id)}}" class="btn btn-warning btn-xs">Editar</a> --}}
            <a href="javascript:;" onclick="eliminar(this);" data-id_buy={{$buy->id}} class="btn btn-danger btn-xs">Eliminar</a>
            </td>
            </tr>
            @endforeach
            @else
            <p class='alert alert-danger'>No hay Ventas</p>
            @endif
            </table>
        </div>

			</div>
			</div>

	</div>
@endsection
@section('scripts')
<script src="{{asset('js/sweetalert.min.js')}}" type="text/javascript"></script>

<script>
    function eliminar(a) {
          swal({
            icon: "warning",
              text: '¿Seguro que deseas eliminar esto?,se borrarán todos los datos relacionados con él,esto no se  puede revertir!".',
              buttons: {
                  cancel: "No,cancelar!",
                  catch: {
                    text: "Sí,eliminar",
                    value: "catch",
                  },
                },
              })
              .then((value) => {
                switch (value) {
                  case "catch":
               let id_buy=$(a).data("id_buy");
               let url="{{route('admin.delete.buy','id')}}"
               url=url.replace("id",id_buy);
                $.ajax({
                url         : url,
                cache       : false,
                contentType : false,
                processData : false,
                type        : 'get',
                dataType:"JSON",
                success     : function(data, textStatus, jqXHR){
                    if (data.result != -1) {
                      swal({
                        tittle:"Excelente!",
                        text:"registro eliminado con éxito",
                        icon :"success",
                      }).then((value) => {
                        location.href='{{route("admin.buys")}}';


                      });

                    }else{

                    }
               
                  }
            });
                    break;
                  default:
                  
                }
              });
        

      }   

    </script>    
@endsection